### ISSUE TITLE
cannot open or save todo txt files - openSUSE Tumbleweed 1.4.0

### ISSUE THREAD

**Issue by spanner888** [mNantern/QTodoTxt#147]
Saved a note - btu file specified is NOT created! - No errors in GUI.

spanner888@linux-vgzm:~/Documents> qtodotxt
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
kfilemodule(18638) KMimeTypeRepository::parents: "/usr/share/mime/subclasses"  refers to unknown mimetype  "application/vnd.ms-excel.sheet.binary.macroEnabled.12" 
kfilemodule(18638) KMimeTypeRepository::parents: "/usr/share/mime/subclasses"  refers to unknown mimetype  "application/vnd.ms-excel.addin.macroEnabled.12" 
kfilemodule(18638) KMimeTypeRepository::parents: "/usr/share/mime/subclasses"  refers to unknown mimetype  "application/vnd.ms-powerpoint.slideshow.macroEnabled.12" 
kfilemodule(18638) KMimeTypeRepository::parents: "/usr/share/mime/subclasses"  refers to unknown mimetype  "application/vnd.ms-excel.sheet.macroEnabled.12" 
kfilemodule(18638) KMimeTypeRepository::parents: "/usr/share/mime/subclasses"  refers to unknown mimetype  "application/vnd.ms-powerpoint.presentation.macroEnabled.12" 
kfilemodule(18638) KMimeTypeRepository::parents: "/usr/share/mime/subclasses"  refers to unknown mimetype  "application/vnd.ms-word.template.macroEnabled.12" 
kfilemodule(18638) KMimeTypeRepository::parents: "/usr/share/mime/subclasses"  refers to unknown mimetype  "application/vnd.ms-excel.template.macroEnabled.12" 
kfilemodule(18638) KMimeTypeRepository::parents: "/usr/share/mime/subclasses"  refers to unknown mimetype  "application/vnd.ms-powerpoint.template.macroEnabled.12" 
kfilemodule(18638) KMimeTypeRepository::parents: "/usr/share/mime/subclasses"  refers to unknown mimetype  "application/vnd.ms-word.document.macroEnabled.12" 
kfilemodule(18638) KMimeTypeRepository::parents: "/usr/share/mime/subclasses"  refers to unknown mimetype  "application/vnd.ms-powerpoint.slide.macroEnabled.12" 

.... now the file save dialog is open - set file name to qtodotxt.txt
    
kfilemodule(18638): couldn't create slave: "Unable to create io-slave:
klauncher said: Unknown protocol ''.
" 
Traceback (most recent call last):
  File "/usr/share/qtodotxt/bin/../qtodotxt/ui/controllers/main_controller.py", line 136, in _tasks_list_taskCreated
    self._onFileUpdated()
  File "/usr/share/qtodotxt/bin/../qtodotxt/ui/controllers/main_controller.py", line 150, in _onFileUpdated
    self.autoSave()
  File "/usr/share/qtodotxt/bin/../qtodotxt/ui/controllers/main_controller.py", line 41, in autoSave
    self.save()
  File "/usr/share/qtodotxt/bin/../qtodotxt/ui/controllers/main_controller.py", line 192, in save
    QtGui.QFileDialog.getSaveFileName(self._view, filter=FILENAME_FILTERS)
ValueError: too many values to unpack (expected 2)

attempting to open in Qtodotx and existing file created via todotxt shell scripts:

qtodotxt/bin/../qtodotxt/ui/controllers/main_controller.py", line 213, in open
    QtGui.QFileDialog.getOpenFileName(self._view, filter=FILENAME_FILTERS)
ValueError: too many values to unpack (expected 2)

More clues:
    - quote title bar alwasy says *untitled
    - success is open file from command line 
            qtodotxt -f /home/spanner888/Documents/todo/todo.txt
            ... and auto save works

**Comment by funkyfuture** [comment]
how did you install qtodotxt and PySide?

**Comment by spanner888** [comment]
I am sorry, don't have any notes on that, and I won't have access to that PC for a few months. Plus at present I am reduced to sharing a small card table for wokspace and don't have any way to try and replicate the environment/issue.

My usual way is to use YAST, then if package not available in YAST, try Opensuse package search, eg http://software.opensuse.org/package/qtodotxt?search_term=qtodotxt, then if still can't find, then by download & build source (not required for qtodotxt - as can find in package search).

Ditto for pyside if it was not already included as a dependency.

Sorry can't help any more ATM.

**Comment by caowick** [comment]
My work-around since I'm not a programmer:  Start QTodoTxt via a terminal in the Dropbox directory and open the existing todo.txt file with the -f flag. This wrote an entry to "last_open_file" in the ~/.qtodotxt.cfg file. Close the program and edit the ~/.qtodotxt.cfg file and change the "last_open_file" to point to the correct file and it seems to work.
